[advisory]
id = "RUSTSEC-2019-0037"
package = "pnet"
date = "2019-06-11"
title = "Compiler optimisation for next_with_timeout in pnet::transport::IcmpTransportChannelIterator flaws to SEGFAULT"
url = "https://github.com/libpnet/libpnet/issues/449"
categories = ["memory-corruption"]
cvss = "CVSS:3.0/AV:L/AC:L/PR:H/UI:N/S:U/C:N/I:H/A:H"
keywords = ["segfault"]
description = """
Affected versions of this crate were optimized out by compiler,
which caused dereference of uninitialized file descriptor which caused segfault.
"""
[affected.functions]
"pnet::transport::IcmpTransportChannelIterator" = ["< 0.26.0"]

[versions]
patched = [">= 0.26.0"] # no patch exists yet
