[advisory]
id = "RUSTSEC-2018-0015"
package = "quickersort"
date = "2019-06-30"
title = "quickersort is deprecated and unmaintained"
informational = "unmaintained"
url = "https://github.com/notriddle/quickersort/commit/0bc164366315801f0c6b31f4081b7df9fc894076"
unaffected_versions = ["> 3.0.1"]
patched_versions = []

description = """
The author of the `quickersort` crate has deprecated it and does not recommend using it anymore.

Everything in it has been incorporated into [std::sort_unstable](https://doc.rust-lang.org/stable/std/primitive.slice.html#method.sort_unstable) in the standard library as of Rust 1.20
"""
