[advisory]
id = "RUSTSEC-2020-0018"
package = "block-cipher-trait"
title = "crate has been renamed to `block-cipher`"
informational = "unmaintained"
date = "2020-05-26"
url = "https://github.com/RustCrypto/traits/pull/139"
description = """
This crate has been renamed from `block-cipher-trait` to `block-cipher`.

The new repository location is at:

<https://github.com/RustCrypto/traits/tree/master/block-cipher>
"""

[versions]
patched = []
unaffected = []
