[advisory]
id = "RUSTSEC-0000-0000"

package = "bigint"

date = "2020-05-07"

title = "Undefined Behavior"

categories = ["memory-corruption"]

keywords = ["ub", "undefined", "uninit"]

description = """
Affected versions of this crate contained multiple Undefined Behaviours
Triggering Undefined Behavior can produce unknown results and thus isn't safe to use
"""

[versions]
patched = []
