[advisory]
id = "RUSTSEC-2020-0051"
package = "rustsec"
title = "Obsolete versions of the `rustsec` crate do not support the new V3 advisory format"
date = "2020-10-01"
url = "https://github.com/RustSec/advisory-db/issues/414"
description = """
If you are seeing this message, you are running an obsolete version of
`cargo-audit` which does not support the new V3 advisory format.
These versions are end-of-life.

This advisory is a notice that that it will soon be unable to parse the
advisory database.

Please upgrade `cargo-audit` to a newer release.
"""

[versions]
unaffected = [">= 0.19.0"]
patched = []
