[advisory]
id = "RUSTSEC-2020-0022"
package = "ozone"
date = "2020-07-04"
title = "Ozone contains several memory safety issues"
description = """
Ozone contains several memory safety issues including [out-of-bound access](https://github.com/bqv/ozone/blob/e21f948b0178ab305f644118f18d87a838c618e0/src/buffer.rs#L38-L48)
and dropping of [uninitialized memory](https://github.com/bqv/ozone/blob/e21f948b0178ab305f644118f18d87a838c618e0/src/map.rs#L94-L101).
"""

[versions]
patched = []
