[advisory]
id = "RUSTSEC-2019-0031"
package = "spin"
title = "spin is no longer actively maintained"
informational = "unmaintained"
date = "2019-11-21"
url = "https://github.com/mvdnes/spin-rs/commit/7516c80"
description = """
The author of the `spin` crate does not have time or interest to maintain it.

Consider the following alternatives (all of which support `no_std`):

- [`conquer-once`](https://github.com/oliver-giersch/conquer-once)
- [`lock_api`](https://crates.io/crates/lock_api) (a subproject of `parking_lot`)
  - [`spinning_top`](https://github.com/rust-osdev/spinning_top) spinlock crate built on `lock_api`
- [`spinning`](https://github.com/4lDO2/spinning-rs)
"""

[versions]
patched = []
unaffected = ["> 0.5.2"] # last release
