blank_issues_enabled: true
contact_links:
  - name: Rust-lang Project Security Policy
    url: https://www.rust-lang.org/policies/security
    about: Please report issues about rustc and cargo to security@rust-lang.org.
