[advisory]
id = "RUSTSEC-2020-0028"
package = "rocket"
date = "2020-05-27"
informational = "unsound"
title = "`LocalRequest::clone` creates multiple mutable references to the same object"
url = "https://github.com/SergioBenitez/Rocket/issues/1312"
description = """
The affected version of `rocket` contains a `Clone` trait implementation of
`LocalRequest` that reuses the pointer to inner `Request` object.
This causes data race in rare combinations of APIs if the original and the
cloned objects are modified at the same time.
"""

[affected]
functions = { "rocket::local::LocalRequest::clone" = ["< 0.4.5, >= 0.4.0"] }

[versions]
patched = [">= 0.4.5"]
unaffected = ["< 0.4.0"]
