[advisory]
id = "RUSTSEC-2020-0005"
package = "redox-os/relibc"
date = "2020-03-10"
title = "Use After Free Bugs in netdb"
url = "https://gitlab.redox-os.org/redox-os/relibc/issues/159"
keywords = ["use-after-free"]
description = """
Affected versions of this crate would access memory through a dangling pointer after the pointed vector was dropped.

This is a use-after-free vulnerability and could allow an attacker to gain arbitrary code execution.

The flaw can be corrected by making the vector static to prevent dropping it.
"""

[affected.functions]
"netdb::gethostbyaddr" = ["<= 0.1.0"]
"netdb::gethostbyname" = ["<= 0.1.0"]
"netdb::getprotoent" = ["<= 0.1.0"]
"netdb::getservent" = ["<= 0.1.0"]

[versions]
patched = []
unaffected = []
