[advisory]
id = "RUSTSEC-0000-0000"
package = "rand"
date = "2019-04-19"
informational = "unsound"
title = "Invalid pointer usage"
description = """
Affected versions of this crate violated pointer provenance rules, resulting in
undefined behavior.
 
The flaw was corrected by Ralf Jung.
"""
patched_versions = [">= 0.7.0"]
unaffected_versions = ["< 0.5.0"]
url = "https://github.com/rust-random/rand/blob/master/CHANGELOG.md#070---2019-06-28"
