[advisory]
id = "CVE-2018-1000657"
package = "std"
date = "2018-08-20"
title = "Buffer overflow vulnerability in VecDeque::reserve()"
categories = ["code-execution", "denial-of-service"]
url = "https://github.com/rust-lang/rust/issues/44800"
description = """
The `std::collections::vec_deque::VecDeque::reserve()` function contains a
buffer overflow vulnerability that can potentially result in arbitrary code
execution.
"""

[affected.functions]
"std::collections::vec_deque::VecDeque::reserve" = ["< 1.22.0, >= 1.3.0"]

[versions]
patched = [">= 1.22.0"]
unaffected = ["< 1.3.0"]
