name: Export to OSV format

on:
  push:
    branches: main

permissions: {}

jobs:
  publish-web:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed for pushing back to the repo
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: osv
          persist-credentials: true # persists the token for git push below

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: admin-cache
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-0ca9edd637bced72d435a282199af47e727276d3

      - name: Install rustsec-admin
        if: steps.admin-cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/rustsec/rustsec rustsec-admin --rev 0ca9edd637bced72d435a282199af47e727276d3

      - run: |
          mkdir -p crates
          rustsec-admin osv crates
          # FIXME: hack to avoid committing advisories without an ID
          rm -f crates/RUSTSEC-0000-0000.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update OSV exported data" || true
          git push || true
