name: Export to OSV format

on:
  push:
    branches: main

permissions: {}

jobs:
  publish-web:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed for pushing back to the repo
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: osv
          persist-credentials: true # persists the token for git push below

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: admin-cache
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-04cc3a7e0e0a81370a08c6f4aea3192255b19275

      - name: Install rustsec-admin
        if: steps.admin-cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/rustsec/rustsec rustsec-admin --rev 04cc3a7e0e0a81370a08c6f4aea3192255b19275

      - run: |
          mkdir -p crates
          rustsec-admin osv crates
          # FIXME: hack to avoid committing advisories without an ID
          rm -f crates/RUSTSEC-0000-0000.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update OSV exported data" || true
          git push || true
