name: Publish Web

on:
  push:
    branches: main

permissions: {}

jobs:
  publish-web:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed for pushing back to the repo
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: gh-pages
          persist-credentials: true # persists the token for git push below

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: admin-cache
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-9909babfe97ac580d59bb48ff8f26308afcd486e

      - name: Install rustsec-admin
        if: steps.admin-cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/rustsec/rustsec rustsec-admin --rev 9909babfe97ac580d59bb48ff8f26308afcd486e

      - run: |
          rustsec-admin web .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update gh-pages" || true
          git push || true
