name: Publish Web

on:
  push:
    branches: master

jobs:
  publish-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-v0.3.4
      - run: |
          if [ ! -f $HOME/.cargo/bin/rustsec-admin ]; then
           cargo install rustsec-admin --vers 0.3.4
          fi
      - run: rustsec-admin web
      - run: git commit -m "Update gh-pages" && git push || true
