name: Publish Web

on:
  push:
    branches: main

permissions: {}

jobs:
  publish-web:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed for pushing back to the repo
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: gh-pages
          persist-credentials: true # persists the token for git push below

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: admin-cache
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-9296b796c38ff8e64c4278d3ae9fd18e42cab1ad

      - name: Install rustsec-admin
        if: steps.admin-cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/rustsec/rustsec rustsec-admin --rev 9296b796c38ff8e64c4278d3ae9fd18e42cab1ad

      - run: |
          rustsec-admin web .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update gh-pages" || true
          git push || true
