name: Validate

on:
  pull_request: {}
  push:
    branches: main

jobs:
  lint:
    name: Lint advisories
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache cargo bin
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin
        key: rustsec-admin-git

    - name: Install rustsec-admin
      run: |
        VERSION="0.8.8"
        cargo install rustsec-admin --git https://github.com/rustsec/rustsec \
          --rev 1e9b1a26401a07ff10045915619c6e538861eeef

    - name: Lint advisories
      run: rustsec-admin lint --skip-namecheck rustdecimal,vec-const
