name: Validate

on:
  pull_request: {}
  push:
    branches: main

permissions: {}

jobs:
  lint:
    name: Lint advisories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install rustsec-admin
        uses: ./.github/actions/install-rustsec-admin

      - name: Lint advisories
        run: rustsec-admin lint
