name: Validate

on:
  pull_request: {}
  push:
    branches: main

permissions: {}

jobs:
  lint:
    name: Lint advisories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Cache cargo bin
        id: admin-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-eee63cf3c3916a9b8305678dfb91206acd9e67eb

      - name: Install rustsec-admin
        if: steps.admin-cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/rustsec/rustsec rustsec-admin --rev eee63cf3c3916a9b8305678dfb91206acd9e67eb

      - name: Lint advisories
        run: rustsec-admin lint
