name: Validate

on:
  pull_request: {}
  push:
    branches: master

jobs:
  lint:
    name: Lint advisories
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache cargo bin
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: rustsec-admin-v0.2.0

    - name: Install rustsec-admin
      run: |
        if [ ! -f $HOME/.cargo/bin/rustsec-admin ]; then
            cargo install rustsec-admin
        fi

    - name: Lint advisories
      run: rustsec-admin lint
